# Generated by Django 5.2.11 on 2026-02-04 23:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cache_key', models.CharField(db_index=True, max_length=96, unique=True)),
                ('params', models.JSONField()),
                ('label', models.CharField(blank=True, max_length=128)),
                ('box_2d', models.JSONField()),
                ('mask_file', models.FileField(blank=True, null=True, upload_to='masks/%Y/%m/%d/')),
                ('cutout_file', models.FileField(blank=True, null=True, upload_to='cutouts/%Y/%m/%d/')),
                ('timings', models.JSONField(default=dict)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='segmenter.upload')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('params', models.JSONField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='segmenter.segmentresult')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='segmenter.upload')),
            ],
        ),
    ]
