# Generated by Django 5.2.11 on 2026-02-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentresult',
            name='candidates',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='segmentresult',
            name='selected_candidate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
